### ISSUE TITLE
ChatGPT issue

### ISSUE THREAD

**Issue by menchian** [kelvin124124/ChatTranslated#1]
When using ChatGPT, if the original text conveys a request for assistance, the translated sentence will be based on the AI’s response to that request, rather than a literal translation of the sentence itself.

This is a situation encountered when translating Japanese into Traditional Chinese. Perhaps using quotation marks to enclose the sentence, for example: 'Please translate "A" into Chinese Trad,' and extract the phrase within the quotes in subsequent operations.

Thx :)

**Comment by kelvin124124** [comment]
I changed the prompt to 
`TRANSLATE FFXIV chat to ${targetLanguage}: message`

instead of just
`FFXIV chat to ${targetLanguage}: message`

This should solve the problem.

**Comment by kelvin124124** [comment]
If you are using the OpenAI API mode, it should get fixed in the next update.
If you are using GPTProxy, it should be fixed by now.

**Comment by menchian** [comment]
Thanks for your work. I will test it later.

**Comment by kelvin124124** [comment]
@menchian would be great if you let me know the testing results
