### ISSUE TITLE
Chat integration spamming into /say

### ISSUE THREAD

**Issue by sunitori** [kelvin124124/ChatTranslated#10]
It seems that when it translates via chat integration and translates from /say it will actually send the CT readable for everyone in say. This is obviously not ideal. Is this intended?

**Comment by kelvin124124** [comment]
@sunitori Translated messages are printed locally. The plugin do not and will not have the ability to send chat directly to everyone. 

Send a screenshot from another account showing it send the chat to everyone if that is not your case.

**Comment by sunitori** [comment]
Thank you for your patience and reassurance. I am sorry for the inconveniences caused cause I know it's annoying to get issues that boil down to the user being dumb. 
I tried to replicate it without success and talked to the involved people. This was a mistake on my end.

I think the issue boils down to coincidences/panic and a weird interaction with the [chat bubbles plugin](https://github.com/Haplo064/ChatBubbles). As CT prints it in your own visible say chat it, it will display above your own head.

Thank you for the great plugin. It's nice to understand people. Sorry for the wasted time.
