### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Linoa235** [kelvin124124/ChatTranslated#32]
Hi, since the last update the plugin no longer wants to translate with Google Free Company etc. directly in the game chat

**Comment by kelvin124124** [comment]
Sorry but I don't understand you English. Please type in your primary language and translate it. Use an AI chatbot to phrase it if possible.

**Comment by Linoa235** [comment]
> Sorry but I don't understand you English. Please type in your primary language and translate it. Use an AI chatbot to phrase it if possible.

The plugin sometimes stops translating in game

**Comment by kelvin124124** [comment]
1. update to the latest version (3.1)
2. if the issue still exists, type `/xllog` in game and copy the relevant logs, or send a screenshot of the log, then send your plugin settings
