### ISSUE TITLE
Possible conflict with Chat Bubbles

### ISSUE THREAD

**Issue by Onisaku** [kelvin124124/ChatTranslated#34]
Hi , with Chat Bubbles active the translation appears in the balloon above the character, as if you were the one writing the translation. Do any options need to be set or could it be a conflict between the two plugins?
thank you for your time.

**Comment by kelvin124124** [comment]
Can you provide an in-game screenshot?

**Comment by Onisaku** [comment]
![Screenshot ](https://github.com/user-attachments/assets/72eaadbc-822c-411b-9553-b83deb26f502)

**Comment by kelvin124124** [comment]
fixed in 3.1.0.3
