### ISSUE TITLE
colored translated phrase

### ISSUE THREAD

**Issue by Onisaku** [kelvin124124/ChatTranslated#41]
in the meantime thanks for the continuous updates,
for a better reading of the chat it could be a good thing to add the option to color the translated phrase in the game chat, basically being able to color the entire phrase of [CT].

Thanks again.

**Comment by kelvin124124** [comment]
will add the option in the next update

**Comment by kelvin124124** [comment]
Added in 3.2.0.1

**Comment by Onisaku** [comment]
hi, I updated and saw the new button, but by activating it the translations are not colored, should a window open to choose the color?  ty

**Comment by kelvin124124** [comment]
I will look into it later

**Comment by kelvin124124** [comment]
Is it not colored? or did I misunderstood your suggestion?

![image](https://github.com/user-attachments/assets/99b143e8-b4c3-47ff-91ea-e375bbfdae9a)

**Comment by kelvin124124** [comment]
actually I did similar things in earlier versions but that causes random crash with unknown reasons. so unfortunately I don't think I will add that to the plugin. the best I can do is to print uncolored messages so they stand out (slightly) from the normal ones.
