### ISSUE TITLE
Chat channel settings don't persist over plugin restarts

### ISSUE THREAD

**Issue by gsapi** [kelvin124124/ChatTranslated#50]
1. Open config
2. Uncheck "Shout" in Chat Channels
3. Disable and enable the plugin
4. Shout is now checked again

**Comment by kelvin124124** [comment]
seems like the plugin is overwriting the channels in the config file every time it is initialized.
will look into it later.

**Comment by kelvin124124** [comment]
fixed in 3.2.1.1
