### ISSUE TITLE
Additional language detection options

### ISSUE THREAD

**Issue by gsapi** [kelvin124124/ChatTranslated#52]
I've recently been finding that the anonymous Google Translate and Bing language detection methods have some harsh rate limiting, to the point where the plugin can become unusable if there's a lot of chat messages to go through.

Could we have additional options for language detection that aren't subject to rate limits? Such as Google's official language detection API, or by modifying the LLM prompt to tell us a message's language before or after translation?

**Comment by kelvin124124** [comment]
I will add other options or backup for language detection in future versions. 
Unfortunately I'm quite busy rn so this have to wait.

**Comment by kelvin124124** [comment]
Now the language detection primarily uses Yandex, with Google and Bing as backup. Hopefully this will solve the problem.
