### ISSUE TITLE
Write in whatever languange

### ISSUE THREAD

**Issue by Yokimitsuro** [kelvin124124/ChatTranslated#54]
can you add a function to write in any languange and translate to other language for the people in the chat???? is that possible? Thanks!

**Comment by kelvin124124** [comment]
If you mean 1. type message in Japanese 2. press enter 3. print English message for everyone 

this is intentionally not added to avoid miscommunication and confusion to other players.

If you mean translating a single sentence this can be done in the plugin main window, then you can copy and send it. Languages apart from Ja, En, Fr, De is not supported to discourage players from sending them on public channels.

**Comment by Yokimitsuro** [comment]
i mean this

"If you mean 1. type message in Japanese 2. press enter 3. print English message for everyone"

because we have many people who do not speak English and cannot communicate :( but i think its ok if you dont want to add it.

Thanks you a lot for your work.
