### ISSUE TITLE
[feature request] chat 2 integration

### ISSUE THREAD

**Issue by hhharkness** [kelvin124124/ChatTranslated#55]
hi! love the idea of this but it doesn't seem to apply if you use chat 2, is making it compatible possible or should i be asking the chat 2 dev? thanks!

**Comment by kelvin124124** [comment]
Last time I checked (6.5) it worked fine. Will check again when I have time.

**Comment by kelvin124124** [comment]
@hhharkness It works on my machine. Can you describe how it's not working on your side?

**Comment by hhharkness** [comment]
sorry for late reply, haven't had time to play for a while. i installed it again and it does seem to be working now, not sure why i couldn't get it to last time i tried! sorry
